import os
def dict_zombies(sprite_base_path):
        sprite_base_path = os.path.join(sprite_base_path, "Sprites")
        sprite_dict_zombies = { 
                
                            "walker1" :{"x1"  : 0,
                                    "y1"  : 1245,
                                    "x2"  : 35,
                                    "y2"  : 1295,
                                    "path": sprite_base_path + r"\InfectedA_LQ.dat"},
                            "walker2" :{"x1"  : 0,
                                    "y1"  : 1245,
                                    "x2"  : 35,
                                    "y2"  : 1295,
                                    "path": sprite_base_path + r"\InfectedA_LQ.dat"},
                            "walker3" :{"x1"  : 0,
                                    "y1"  : 1245,
                                    "x2"  : 35,
                                    "y2"  : 1295,
                                    "path": sprite_base_path + r"\InfectedA_LQ.dat"},
                            
                            "medium1" :{"x1"  : 1815,
                                    "y1"  : 1450,
                                    "x2"  : 1845,
                                    "y2"  : 1500,
                                    "path": sprite_base_path + r"\InfectedA_LQ.dat"},
                            "medium2" :{"x1"  : 1815,
                                    "y1"  : 1450,
                                    "x2"  : 1845,
                                    "y2"  : 1500,
                                    "path": sprite_base_path + r"\InfectedA_LQ.dat"},
                            "medium3" :{"x1"  : 1815,
                                    "y1"  : 1450,
                                    "x2"  : 1845,
                                    "y2"  : 1500,
                                    "path": sprite_base_path + r"\InfectedA_LQ.dat"},
                            "runner4" :{"x1"  : 1815,
                                    "y1"  : 1450,
                                    "x2"  : 1845,
                                    "y2"  : 1500,
                                    "path": sprite_base_path + r"\InfectedA_LQ.dat"},
                            "runner5" :{"x1"  : 1815,
                                    "y1"  : 1450,
                                    "x2"  : 1845,
                                    "y2"  : 1500,
                                    "path": sprite_base_path + r"\InfectedA_LQ.dat"},
                            
                            "Strong1" :{"x1"  : 1230,
                                            "y1"  : 3815,
                                            "x2"  : 1263,
                                            "y2"  : 3870,
                                            "path": sprite_base_path + r"\InfectedA_LQ.dat"},
                            "Strong2" :{"x1"  : 1230,
                                            "y1"  : 3815,
                                            "x2"  : 1263,
                                            "y2"  : 3870,
                                            "path": sprite_base_path + r"\InfectedA_LQ.dat"},
                            "Strong3" :{"x1"  : 1230,
                                            "y1"  : 3815,
                                            "x2"  : 1263,
                                            "y2"  : 3870,
                                            "path": sprite_base_path + r"\InfectedA_LQ.dat"},
                            "executive4" :{"x1"  : 1230,
                                            "y1"  : 3815,
                                            "x2"  : 1263,
                                            "y2"  : 3870,
                                            "path": sprite_base_path + r"\InfectedA_LQ.dat"},
                            
                            "Harpies1" :{"x1"  : 0,
                                        "y1"  : 1450,
                                        "x2"  : 40,
                                        "y2"  : 1495,
                                        "path": sprite_base_path + r"\InfectedB_LQ.dat"},
                            "Harpies2" :{"x1"  : 0,
                                        "y1"  : 1450,
                                        "x2"  : 40,
                                        "y2"  : 1495,
                                        "path": sprite_base_path + r"\InfectedB_LQ.dat"},
                            "Harpies3" :{"x1"  : 0,
                                        "y1"  : 1450,
                                        "x2"  : 40,
                                        "y2"  : 1495,
                                        "path": sprite_base_path + r"\InfectedB_LQ.dat"},
                            "Powerful1" :{"x1"  : 0,
                                        "y1"  : 1450,
                                        "x2"  : 40,
                                        "y2"  : 1495,
                                        "path": sprite_base_path + r"\InfectedB_LQ.dat"},
                            
                            "Powerful2" :{"x1"  : 0,
                                        "y1"  : 1450,
                                        "x2"  : 40,
                                        "y2"  : 1495,
                                        "path": sprite_base_path + r"\InfectedB_LQ.dat"},
                            
                            "Chubbies1" :{"x1"  : 135,
                                    "y1"  : 3440,
                                    "x2"  : 181,
                                    "y2"  : 3492,
                                    "path": sprite_base_path + r"\InfectedB_LQ.dat"},
                            
                            "Chubbies2" :{"x1"  : 135,
                                    "y1"  : 3440,
                                    "x2"  : 181,
                                    "y2"  : 3492,
                                    "path": sprite_base_path + r"\InfectedB_LQ.dat"},
                            
                            "Chubbies3" :{"x1"  : 135,
                                    "y1"  : 3440,
                                    "x2"  : 181,
                                    "y2"  : 3492,
                                    "path": sprite_base_path + r"\InfectedB_LQ.dat"},
                            
                            "Venoms1" :{"x1"  : 3125,
                                    "y1"  : 3430,
                                    "x2"  : 3175,
                                    "y2"  : 3480,
                                    "path": sprite_base_path + r"\InfectedC_LQ.dat"},
                            "Venoms2" :{"x1"  : 3125,
                                    "y1"  : 3430,
                                    "x2"  : 3175,
                                    "y2"  : 3480,
                                    "path": sprite_base_path + r"\InfectedC_LQ.dat"},
                            "Venoms3" :{"x1"  : 3125,
                                    "y1"  : 3430,
                                    "x2"  : 3175,
                                    "y2"  : 3480,
                                    "path": sprite_base_path + r"\InfectedC_LQ.dat"},
                            "spitter4" :{"x1"  : 3125,
                                    "y1"  : 3430,
                                    "x2"  : 3175,
                                    "y2"  : 3480,
                                    "path": sprite_base_path + r"\InfectedC_LQ.dat"},
                            
                            "Ultra"
                                        : {"x1"  : 2175,
                                           "y1"  : 1720,
                                           "x2"  : 2247,
                                           "y2"  : 1795,
                                           "path": sprite_base_path  + r"\InfectedGiant_LQ.dat",
                                           "cell_size": 3},

        } 
        return sprite_dict_zombies

def dict_entities(sprite_base_path):
    images_base_path  = os.path.join(sprite_base_path, "Images")
    interactive_base_path  = os.path.join(images_base_path, "InteractiveObjects")
    geology_base_path = os.path.join(images_base_path, "Geology")
    tiles_base_path = os.path.join(images_base_path, "Tiles")
    sprite_base_path  = os.path.join(sprite_base_path, "Sprites")
    entities = {
        "OilSource"
                :{"x1"  : 1085,
                  "y1"  : 783,
                  "x2"  : 1230,
                  "y2"  : 880,
                  "path": geology_base_path + r"\Atlas1_LQ.dat",
                  "cell_size": 2},
        "DoomBuildingSmall"                 
                :{"x1"  : 2095,
                  "y1"  : 0,
                  "x2"  : 2250,
                  "y2"  : 150,
                  "path": sprite_base_path + r"\BuildingsB_LQ.dat"},
        "DoomBuildingMedium"                 
                :{"x1"  : 1920,
                  "y1"  : 0,
                  "x2"  : 2080,
                  "y2"  : 150,
                  "path": sprite_base_path + r"\BuildingsB_LQ.dat"},
        "DoomBuildingLarge"                 
                :{"x1"  : 895,
                  "y1"  : 0,
                  "x2"  : 1150,
                  "y2"  : 285,
                  "path": sprite_base_path + r"\BuildingsB_LQ.dat"},
        "RailWayCellH"
                :{"x1"  : 0,
                  "y1"  : 0,
                  "x2"  : 224,
                  "y2"  : 224,
                  "path": tiles_base_path + r"\2128739667.dxtexture"},
        "RailWayTerminatorW"
                :{"x1"  : 0,
                  "y1"  : 0,
                  "x2"  : 224,
                  "y2"  : 224,
                  "path": tiles_base_path + r"\2128739667.dxtexture"},
        "RailWayTerminatorE"
                :{"x1"  : 0,
                  "y1"  : 0,
                  "x2"  : 224,
                  "y2"  : 224,
                  "path": tiles_base_path + r"\2128739667.dxtexture"},
        "RailWayTerminatorN"
                :{"x1"  : 0,
                  "y1"  : 0,
                  "x2"  : 224,
                  "y2"  : 224,
                  "path": tiles_base_path + r"\2128739667.dxtexture",
                  "rotate": 90},
        "RailWayTerminatorS"
                :{"x1"  : 0,
                  "y1"  : 0,
                  "x2"  : 224,
                  "y2"  : 224,
                  "path": tiles_base_path + r"\2128739667.dxtexture",
                  "rotate": 90},
        "RailWayCellV"
                :{"x1"  : 0,
                  "y1"  : 0,
                  "x2"  : 224,
                  "y2"  : 224,
                  "path": tiles_base_path + r"\2128739667.dxtexture",
                  "rotate": 90},
        "ZombieGiant"
                :{"x1"  : 2175,
                  "y1"  : 1720,
                  "x2"  : 2247,
                  "y2"  : 1795,
                  "path": sprite_base_path  + r"\InfectedGiant_LQ.dat"},
    } 
    return entities